repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: stylelint-css
        name: stylelint with autofix
        entry: ./stylelint-wrapper.sh
        language: node
        types: [css]
        files: \.css$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        language_version: python3
