version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - netumo-net
    restart: always

  frontend1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend1
    volumes:
      - dbdata:/app/database  # shared volume for json-server db.json persistence
    networks:
      - netumo-net

  frontend2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net

  frontend3:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend3
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net

volumes:
  dbdata:

networks:
  netumo-net:
    driver: bridge
