version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - netumo-net
    restart: always

  frontend1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend1
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net
    ports:
      - "80"

  frontend2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net
    ports:
      - "80"

  frontend3:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend3
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net
    ports:
      - "80"

  postgres:
    build: ./postgresql
    container_name: db
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_LISTEN_ADDRESSES=0.0.0.0
    networks:
      - netumo-net
    expose:
      - "5432"
    volumes:
      - postgresdata:/bitnami/postgresql

  pgbouncer:
    build:
      context: ./pgbouncer
      dockerfile: Dockerfile
    container_name: pool
    environment:
      - PGBOUNCER_AUTH_USER=${PGBOUNCER_USER}
      - PGBOUNCER_AUTH_PASSWORD=${PGBOUNCER_PASSWORD}
      - PGBOUNCER_DATABASE=${DATABASE}
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USERNAME=${PGBOUNCER_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - netumo-net
    expose:
      - "6432"

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE=${DATABASE}
      - PGBOUNCER_USER=${PGBOUNCER_USER}
      - PGBOUNCER_PASSWORD=${PGBOUNCER_PASSWORD}
    depends_on:
      - pgbouncer
    networks:
      - netumo-net
    expose:
      - "80"

  redis:
    image: redis:7-alpine
    container_name: my-redis-cache
    networks:
      - netumo-net
    expose:
      - "6379"
    volumes:
      - redisdata:/data
volumes:
  dbdata:
  postgresdata:
  redisdata:
networks:
  netumo-net:
    driver: bridge
