version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - netumo-net
    restart: always

  frontend1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend1
    volumes:
      - dbdata:/app/database  # shared volume for json-server db.json persistence
    networks:
      - netumo-net

  frontend2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net

  frontend3:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend3
    volumes:
      - dbdata:/app/database
    networks:
      - netumo-net

  postgres:
    build: ./postgresql
    container_name: db
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_LISTEN_ADDRESSES=127.0.0.1
    networks:
      - netumo-net
    expose:
      - "5432"
    volumes:
      - postgresdata:/bitnami/postgresql

  pgbouncer:
    build: ./pgbouncer
    container_name: pool
    environment:
      - PGBOUNCER_AUTH_USER=${PGBOUNCER_USER}
      - PGBOUNCER_AUTH_PASSWORD=${PGBOUNCER_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    depends_on:
      - postgres
    networks:
      - netumo-net
    expose:
      - "6432"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - pgbouncer
    networks:
      - netumo-net
    ports:
      - "5000:5000"


volumes:
  dbdata:
  postgresdata:
networks:
  netumo-net:
    driver: bridge
